setup(
    name='rock_paper_scissors',
    version='0.1.0',
    packages=find_packages(),
    install_requires=[
        'pandas==1.4.3',
        'numpy==1.21.5',
        'matplotlib==3.5.1',
        'seaborn==0.11.2',
        'scikit-0learn==1.0.2',
        'python==3.8'
    ],
)